# Generated by Django 3.0 on 2022-01-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog/images')),
                ('tag', models.CharField(max_length=32)),
                ('created_at', models.DateField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
